In [ ]:
### Integrantes (nombres completos):

# Sharon Gutierrez Perea

## Parte 1: Exploración de Datos con Pandas  

1. Carga el dataset en un DataFrame de Pandas.


In [ ]:
import pandas as pd

# Assuming the dataset is in the Colab environment at this path
ruta = '/content/Pokemon.csv'

df_Pokemon = pd.read_csv(ruta)

2. Muestra las primeras 5 filas del dataset.

In [ ]:
df_Pokemon.head()
# Primeras 5 filas

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

3. ¿Cuántos valores nulos hay en cada columna?

In [ ]:
df_Pokemon.isna().sum()
# 386 valores nulos

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

4. Reemplaza los valores nulos en la columna `Type 2` por `"Unknown"`.

In [ ]:
# Reemplazar null por unknown
df_Pokemon['Type 2'] = df_Pokemon['Type 2'].fillna('Unknown')

# Para confirmarlos cambios:
df_Pokemon['Type 2'].isna().sum()

np.int64(0)

5. ¿Cuántos Pokémon hay de cada tipo principal (`Type 1`)?

In [ ]:
Tipos_de_Pokemon_Tipo_1 = df_Pokemon['Type 1'].nunique()
print(f'Existen {Tipos_de_Pokemon_Tipo_1} Pokémons de tipo principal')

Existen 18 Pokémons de tipo principal


6. ¿Cuántos Pokémon legendarios hay?

In [ ]:
lengendarios = (df_Pokemon['Legendary'] == True).sum()
print(f'Existen {lengendarios} Pokémons legendarios')

Existen 65 Pokémons legendarios


7. Obtén el promedio de cada estadística de combate (`HP`, `Attack`, `Defense`, etc.).

In [ ]:
promedio_HP = df_Pokemon['HP'].mean()
promedio_Attack = df_Pokemon['Attack'].mean()
promedio_Defense = df_Pokemon['Defense'].mean()
promedio_Sp_Atk = df_Pokemon['Sp. Atk'].mean()
promedio_Sp_Def = df_Pokemon['Sp. Def'].mean()
promedio_Speed = df_Pokemon['Speed'].mean()

print(f'El promedio de HP es: {promedio_HP}')
print(f'El promedio de Attack es: {promedio_Attack}')
print(f'El promedio de Defense es: {promedio_Defense}')
print(f'El promedio de Sp. Atk es: {promedio_Sp_Atk}')
print(f'El promedio de Sp. Def es: {promedio_Sp_Def}')
print(f'El promedio de Speed es: {promedio_Speed}')

El promedio de HP es: 69.25875
El promedio de Attack es: 79.00125
El promedio de Defense es: 73.8425
El promedio de Sp. Atk es: 72.82
El promedio de Sp. Def es: 71.9025
El promedio de Speed es: 68.2775


8. ¿Cuál es el Pokémon con la mayor velocidad (`Speed`)?

In [ ]:
from os import name
Velocidad_maxima = df_Pokemon['Speed'].max()
Pokémon_más_rapido = df_Pokemon[df_Pokemon['Speed'] == Velocidad_maxima]


print(f'El Pokémon con la mayor velocidad es: {Pokémon_más_rapido["Name"].values[0]} con {Pokémon_más_rapido["Speed"].values[0]}')

El Pokémon con la mayor velocidad es: DeoxysSpeed Forme con 180


9. Filtra los Pokémon de tipo `"Fire"` con ataque (`Attack`) mayor a 80.

In [ ]:
fire_attack = df_Pokemon[((df_Pokemon['Type 1'] == 'Fire') | (df_Pokemon['Type 2'] == 'Fire')) & (df_Pokemon['Attack'] > 80)]
display(fire_attack[['Name', 'Type 1', 'Type 2', 'Attack']])

Name   Type 1    Type 2  Attack
6                    Charizard     Fire    Flying      84
7    CharizardMega Charizard X     Fire    Dragon     130
8    CharizardMega Charizard Y     Fire    Flying     104
64                    Arcanine     Fire   Unknown     110
83                      Ponyta     Fire   Unknown      85
84                    Rapidash     Fire   Unknown     100
135                     Magmar     Fire   Unknown      95
147                    Flareon     Fire   Unknown     130
158                    Moltres     Fire    Flying     100
171                 Typhlosion     Fire   Unknown      84
247                   Houndoom     Dark      Fire      90
248      HoundoomMega Houndoom     Dark      Fire      90
263                      Entei     Fire   Unknown     115
270                      Ho-oh     Fire    Flying     130
277                  Combusken     Fire  Fighting      85
278                   Blaziken     Fire  Fighting     120
279      BlazikenMega Blaziken     Fire  Fighting     160
353                   Camerupt     Fire    Ground     100
354      CameruptMega Camerupt     Fire    Ground     120
355                    Torkoal     Fire   Unknown      85
424      GroudonPrimal Groudon   Ground      Fire     180
437                  Infernape     Fire  Fighting     104
518                  Magmortar     Fire   Unknown      95
542                    Heatran     Fire     Steel      90
553                    Victini  Psychic      Fire     100
558                    Pignite     Fire  Fighting      93
559                     Emboar     Fire  Fighting     123
573                   Simisear     Fire   Unknown      98
614                   Darumaka     Fire   Unknown      90
615    DarmanitanStandard Mode     Fire   Unknown     140
692                    Heatmor     Fire   Unknown      97
697                   Larvesta      Bug      Fire      85
706                   Reshiram   Dragon      Fire     120
731                 Talonflame     Fire    Flying      81
799                  Volcanion     Fire     Water     110

10. Crea una nueva columna que indique si un Pokémon tiene una estadística total (`Total`) mayor al promedio.  

In [ ]:
promedio_total = df_Pokemon['Total'].mean()
df_Pokemon['Estadística Total'] = df_Pokemon['Total'] > promedio_total
display(df_Pokemon)

#                   Name   Type 1   Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass   Poison    318  45      49       49   
1      2                Ivysaur    Grass   Poison    405  60      62       63   
2      3               Venusaur    Grass   Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass   Poison    625  80     100      123   
4      4             Charmander     Fire  Unknown    309  39      52       43   
..   ...                    ...      ...      ...    ...  ..     ...      ...   
795  719                Diancie     Rock    Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock    Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic    Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic     Dark    680  80     160       60   
799  721              Volcanion     Fire    Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Estadística Total  
0         65       65     45           1      False              False  
1         80       80     60           1      False              False  
2        100      100     80           1      False               True  
3        122      120     80           1      False               True  
4         60       50     65           1      False              False  
..       ...      ...    ...         ...        ...                ...  
795      100      150     50           6       True               True  
796      160      110    110           6       True               True  
797      150      130     70           6       True               True  
798      170      130     80           6       True               True  
799      130       90     70           6       True               True  

[800 rows x 14 columns]

---

## Parte 2: Análisis con Numpy  

11. Convierte las columnas de estadísticas (`HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`) en un array de Numpy.  

In [ ]:
import numpy as np
df_Pokemon_Numpy = df_Pokemon.copy()
df_Pokemon_Numpy = df_Pokemon_Numpy.to_numpy()
array_stats = df_Pokemon_Numpy[:, 5:11]
print(array_stats)

[[45 49 49 65 65 45]
 [60 62 63 80 80 60]
 [80 82 83 100 100 80]
 ...
 [80 110 60 150 130 70]
 [80 160 60 170 130 80]
 [80 110 120 130 90 70]]


12. Calcula la media, mediana y desviación estándar de cada estadística usando Numpy.  

In [ ]:
columnas_de_estadisticas = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']
for i, columna in enumerate(columnas_de_estadisticas):
    media = np.mean(array_stats[:, i])
    mediana = np.median(array_stats[:, i])
    desviacion_estandar = np.std(array_stats[:, i])
    print(f'Estadísticas para {columna}:')
    print(f'  Media: {media}')
    print(f'  Mediana: {mediana}')
    print(f'  Desviación Estándar: {desviacion_estandar}')
    print("-" * 20)

Estadísticas para HP:
  Media: 69.25875
  Mediana: 65.0
  Desviación Estándar: 25.518704873827332
--------------------
Estadísticas para Attack:
  Media: 79.00125
  Mediana: 75.0
  Desviación Estándar: 32.43707367253555
--------------------
Estadísticas para Defense:
  Media: 73.8425
  Mediana: 70.0
  Desviación Estándar: 31.164004777146335
--------------------
Estadísticas para Sp. Atk:
  Media: 72.82
  Mediana: 65.0
  Desviación Estándar: 32.70183633987544
--------------------
Estadísticas para Sp. Def:
  Media: 71.9025
  Mediana: 70.0
  Desviación Estándar: 27.811517286009394
--------------------
Estadísticas para Speed:
  Media: 68.2775
  Mediana: 65.0
  Desviación Estándar: 29.042305241664295
--------------------


13. Normaliza las estadísticas dividiendo cada valor por el máximo de su columna.

In [ ]:
# Calcular el máximo valor
máximo_stats = np.max(array_stats, axis=0)

# Dividiendo cada valor por el máximo de su columna.
Resultado_normalizado = array_stats / máximo_stats

print(Resultado_normalizado)

[[0.17647058823529413 0.2578947368421053 0.21304347826086956
  0.33505154639175255 0.2826086956521739 0.25]
 [0.23529411764705882 0.3263157894736842 0.27391304347826084
  0.41237113402061853 0.34782608695652173 0.3333333333333333]
 [0.3137254901960784 0.43157894736842106 0.36086956521739133
  0.5154639175257731 0.43478260869565216 0.4444444444444444]
 ...
 [0.3137254901960784 0.5789473684210527 0.2608695652173913
  0.7731958762886598 0.5652173913043478 0.3888888888888889]
 [0.3137254901960784 0.8421052631578947 0.2608695652173913
  0.8762886597938144 0.5652173913043478 0.4444444444444444]
 [0.3137254901960784 0.5789473684210527 0.5217391304347826
  0.6701030927835051 0.391304347826087 0.3888888888888889]]


14. Encuentra los índices de los 5 Pokémon con mayor defensa (`Defense`).  

In [ ]:
indices_top_5 = np.argsort(array_stats[:, 2])[-5:]
print(f'Los índices de los 5 Pokémon con mayor defensa son: {indices_top_5}')

Los índices de los 5 Pokémon con mayor defensa son: [414 223 333 230 224]


15. Calcula la correlación entre `Attack` y `Defense`.

In [ ]:
attack = df_Pokemon["Attack"].to_numpy()
defense = df_Pokemon["Defense"].to_numpy()
corre = np.corrcoef(attack,defense)[0,1]
print(f"La corrlación entre Defensa y Ataque es: {round(corre,4)}")

La corrlación entre Defensa y Ataque es: 0.4387


16. Usa Numpy para encontrar cuántos Pokémon tienen una suma de (`HP`, `Attack` y `Defense`) superior a 300.

In [ ]:
# (HP, Attack y Defense)
hp_attack_defense = array_stats[:, :3]

suma = np.sum(hp_attack_defense, axis=1)

count_greater_than_300 = np.sum(suma > 300)

print(f"El numero de Pokémons con una suma mayor a 300 de HP, Attack y Defense son: {count_greater_than_300}")

El numero de Pokémons con una suma mayor a 300 de HP, Attack y Defense son: 94
